name: FriendlyDeathChest
version: 1.0.2
main: io.mckenz.friendlydeathchest.FriendlyDeathChest
api-version: '1.21'
author: McKenzieJDan
description: Creates a chest with player's items upon death instead of dropping them 