name: FriendlyDeathChest
version: '${project.version}'
main: io.mckenz.friendlydeathchest.FriendlyDeathChest
api-version: '1.21'
author: McKenzieJDan
description: Creates a chest with player's items upon death instead of dropping them 